REACTION_OPTIONS = {
    "amplifier": {},
    "analoggenerator": {},
    "compressor": {},
    "dcblocker": {},
    "delay": {},
    "distortion": {},
    "drumsynth": {},
    "echo": {},
    "eq": {},
    "feedback": {},
    "filter": {"nobefore": [":vocal", "vocal"], "noafter": ["pro", "pro:"]},
    "filterpro": {"nobefore": ["vocal"]},
    "flanger": {},
    "fm": {"withspaces": True},
    "generator": {"nobefore": [":analog", "analog"]},
    "glide": {},
    "gpio": {},
    "input": {},
    "kicker": {},
    "lfo": {},
    "loop": {},
    "metamodule": {},
    "modulator": {},
    "multictl": {},
    "multisynth": {},
    "output": {},
    "pitch2ctl": {},
    "pitchshifter": {},
    "reverb": {},
    "sampler": {},
    "sound2ctl": {},
    "spectravoice": {},
    "velocity2ctl": {},
    "vibrato": {},
    "vocalfilter": {"noafter": ["pro"]},
    "vorbisplayer": {},
    "waveshaper": {},
}
